language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAIY72BYOTX7AYCKAA
    - AWS_DEFAULT_REGION=ap-southeast-2

    - LAMBDA_NAME=snsToSlack
    - LAMBDA_DESCRIPTION="Sends SNS notifications to a Slack channel."
    - LAMBDA_TIMEOUT=30
    - LAMBDA_ROLE=arn:aws:iam::300761597318:role/genericLambdaRole

    - LAMBDA_RUNTIME=nodejs6.10
    - LAMBDA_MODULE=index
    - LAMBDA_HANDLER=handler

    # AWS_SECRET_ACCESS_KEY
    - secure: TvHT7cop4qTnzcOxMj0lislraASMouWgeg/ahRpdkpmo9JnWbuukzRv6OaW0MCewhpOnh/IdbLIL5amHUqI6zd8vzBXlKe2d4dggNJcgwe6M+KXjSY7kl8laJ6BtVlzYiNWyT5+HkqqgzHd/PwT4ZGGIp29GEOq2/kX9S1OVcAdQyB9v6LCRy8mcSee8lu7YiUtpUx+pymfQIVyF6MY2uhXdOV+/2MiXFaeAZDSXrEtyFV7+FIcojV1/6XpfLEIo2C+1LU3iRUjkw8FMQcxX/A+dkCo59oe1ClmQM6tvrsIW9bNl029mWgUVjG3Hr6gtcUXnb8efGIZU96sMPfdZSN9HwrmON7uJPGF2ddG4im4JWtsL5DEy4HebXfrZY4CI2ds7L7dR5otkuCCSjnNY4p7W/VzLSQkTt7C2eGK1RPJGdakR7RQTYShI6/lebua95PiieKQpj3OXHVFQ45XGSJYEnPJcCtpGmRe3oZteKizDhwbt6ChbA6uqYiCsEgprNtymEcAZUpXoGxbA3aHPBsfFPU7bvu4Ze4cvvgClbdlChBxLbos6va7RMS6rMxIYJopohZ1jO/9KRM6P1mr28eytNdkYc4rTFJkSHV/v8aYHR/ey+ehnPxmQ0afsW03oiH3KSqUV1yUcuHlEYvMVvctIUdDmP9wTrTQIR0KFjWo=

cache:
  yarn: true
  directories:
    - node_modules

install: true
script: true

before_deploy:
  - yarn remove aws-sdk
  - rm -rf coverage node_modules .*rc.js
  - yarn --prod

deploy:

  - on:
      branch: chromatix
    publish: true

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    description: $LAMBDA_DESCRIPTION
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    module_name: $LAMBDA_MODULE
    handler_name: $LAMBDA_HANDLER
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
