language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAID4ZQD3CFEHFJCKA
    - AWS_DEFAULT_REGION=ap-southeast-2

    - LAMBDA_NAME=awsBillingToSlack
    - LAMBDA_DESCRIPTION="Sends Billing SNS notifications to a Slack channel."
    - LAMBDA_TIMEOUT=30
    - LAMBDA_ROLE=arn:aws:iam::300761597318:role/genericLambdaRole

    - LAMBDA_RUNTIME=nodejs6.10
    - LAMBDA_MODULE=index
    - LAMBDA_HANDLER=handler

    # AWS_SECRET_ACCESS_KEY
    - secure: "gQB/nbB97wfRi8K2vdC9JBVg1uTYF3CQoqGtbeVzpvn85kqdxulrilxQHC2v4QLxAOtkF27dlLO/BMVbcSGkqe0g2bDQts2Y0JZ/lwQ/OHf4HrkpDvwHFz2tmYusAoL7HWJRCVz3xuCl4Klw3QHRtlWlidlZnggfngwrNzuJ2SydMWeNyxK1uriFiGaZfQjU26aTVsY63nc++e54dnCwbSs5nCbc4DM3NkuiR+rFMY1WRRztJPUgevHWVm/R4OfmelEIzLxsszbMGW5HltrGHNXtIM7j4cB5t+ZULHmzti4j6j8dVCFau29cXLJohcJEnkYXj4Y8g9oXZF/wwhWoMVC2DrihYqnW/oKP2eJ9DgWXWZcOqm5eC5GnW2ADrfNAZepYl4PwXbkM6peb3fbsLYrgb2Mr/y0jF2RH35/bC4/lRJ6sQZ+7lf3PoPf16wEcgG5D2WbncDb3uqjBvB21eS7Q2fQYSdQKMKZ/XDgwvxzmYFUUmh11AebCsx1JOOxM5YEQHgEkLw5KVv5f6GVuqacilTCq/PJzlkUCXn/3GT5WL7rgXfxe2bHT9avxrsA/4SKp353+hn7yP2sXtGtGBW9ll8DQ2nKPr9kfLG+RlIZnqA1zM3qxrFx/QJu6csjfu126MSy72KMUFUpLy8r2XuXDbFvwMbwiPzDNNF3qwDY="

cache:
  yarn: true
  directories:
    - node_modules

install: true
script: true

before_deploy:
  - yarn remove aws-sdk
  - rm -rf coverage node_modules .*rc.js
  - yarn --prod

deploy:

  - on:
      branch: aws-billing
    publish: true

    provider: lambda
    function_name: $LAMBDA_NAME
    region: $AWS_DEFAULT_REGION
    role: $LAMBDA_ROLE
    description: $LAMBDA_DESCRIPTION
    runtime: $LAMBDA_RUNTIME
    timeout: $LAMBDA_TIMEOUT
    module_name: $LAMBDA_MODULE
    handler_name: $LAMBDA_HANDLER
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    skip_cleanup: true

notifications:
  email: false
  webhooks:
    urls:
      - https://chr-cicd.herokuapp.com/hooks/travis.php
    on_start: always
